- id: csquotes
  name: All quotation marks should use csquotes
  description: Ensure the use of LaTeX csquotes and prohibits manual quotation marks.
  entry: "``.*''"
  language: pygrep
  files: \.tex$
- id: cleveref-capitalization
  name: Ensure the correct usage of \cref
  description: Ensure that \Cref at a sentence start is capitalized and nowhere else in the sentence.
  entry: "^((\\s*\\\\cref)|[^%\\s]+\\\\Cref).*$"
  language: pygrep
  files: \.tex$
- id: tilde-cite
  name: Each \cite needs a ~
  description: Line breaks should never occur before the citation, thus they need to be protected with the ~.
  entry: "[^~]\\\\cite"
  language: pygrep
  files: \.tex$
- id: american-eg-ie
  name: US English requires a comma after "e.g." and "i.e."
  description: US English requires a comma after "e.g." and "i.e."
  entry: "((e\\.g\\.)|(i\\.e\\.))[^,]"
  language: pygrep
  files: \.tex$
- id: no-space-in-cite
  name: "Ensure there are no whitespace characters in the \\cite command"
  entry: '\\cite\{([^\}]*\s)+[^\}]*\}'
  language: pygrep
  files: \.tex$
- id: consistent-spelling
  name: Ensure consistency between different spelling variants
  description: Ensure that all variants (specified by regex) are written the same way.
  entry: consistent_spelling
  language: python
  files: \.tex$
  require_serial: true
  language_version: python3
- id: ensure-labels-for-sections
  name: Ensure each section has a matching label
  entry: ensure-labels
  language: rust
  files: \.tex$
- id: cispa-syssec-forbidden-words
  name: Forbidden words for CISPA SysSec
  entry: 'blacklist|whitelist'
  language: pygrep
  files: \.tex$
- id: sort-bib
  name: Ensures bibliography is sorted
  entry: 'sort_bib'
  language: python
  language_version: python3
  additional_dependencies: [pybtex]
  files: \.bib$
  stages: [commit, manual]
